spring:
  # Database 설정
  datasource:
    url: jdbc:h2:tcp://localhost/../data/jpashop;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        # 지연 로딩이 적용된 엔티티 또는 컬렉션을 초기화할 때, 한 번의 조회 쿼리의 IN 절에 포함할 식별자의 최대 수 설정
        default_batch_fetch_size: 100

# 로깅 설정
logging:
  level:
    org.hibernate.sql: trace
    org.hibernate.orm.jdbc.bind: trace